global:
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@viticulture-platform.local'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'

route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'default-receiver'
  routes:
    - matchers:
        - alertname =~ "Critical.*"
      receiver: 'critical-receiver'
      group_interval: 5m
      repeat_interval: 30m

receivers:
  - name: 'default-receiver'
    email_configs:
      - to: 'admin@viticulture-platform.local'
        send_resolved: true
  - name: 'critical-receiver'
    email_configs:
      - to: 'alerts-critical@viticulture-platform.local'
        send_resolved: true
    webhook_configs:
      - url: 'http://notification-service:8085/webhook/alert'

inhibit_rules:
  - source_matchers:
      - severity = "critical"
    target_matchers:
      - severity = "warning"
    equal: ['alertname', 'job']